name: agrotec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.2
  syncfusion_flutter_pdf: ^30.2.6
  flutter_riverpod: ^3.0.0
  pdf: ^3.11.3
  file_selector: ^1.0.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  window_size: ^0.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
